#!/bin/ksh

daemon="/usr/local/bin/minetestserver"
daemon_flags="--config /etc/minetest.conf --logfile /var/games/minetest/minetest.log"
daemon_user="_minetest"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1

